--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code
project_pubhost: deveiate.org
project_homepage: http://bitbucket.org/ged/configurability
gem_pubhost: rubygems.org
project_requirements: {}

release_smtphost: mail.faeriemud.org
project_description: |-
  Configurability is a mixin that allows you to add 
  configurability to one or more classes, assign them 
  each a section of the configuration, and then when 
  the configuration is loaded, the class is given the 
  section it requested.
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: {}

project_summary: A configurability mixin for Ruby
version_file: configurability.rb
additional_pkgfiles: []

required_ruby_version: ""
dev_dependencies: {}

authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: ""
project_name: configurability
